apiVersion: v1
kind: Service
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "zigbee2mqtt.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP