version: 2
updates:
    - package-ecosystem: npm
      versioning-strategy: increase
      directory: /
      schedule:
          interval: weekly
      target-branch: dev
      commit-message:
        prefix: fix(ignore)
      groups:
          minor-patch:
              applies-to: version-updates
              update-types:
                  - minor
                  - patch
    - package-ecosystem: docker
      directory: /docker
      schedule:
        interval: weekly
      target-branch: dev
    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: weekly
      target-branch: dev
