packages:
  - .

minimumReleaseAgeExclude:
  - zigbee-herdsman
  - zigbee-herdsman-converters
  - zigbee2mqtt-windfront
  - zigbee2mqtt-frontend

allowBuilds:
  '@serialport/bindings-cpp': true
  esbuild: true
  unix-dgram: true
