FROM alpine:3.7

# Copy files
ADD . /app
RUN cp /app/data/configuration.yaml /app
RUN cp /app/docker/run.sh /app
RUN chmod +x /app/run.sh
WORKDIR /app

# Install dependencies
RUN apk add --update --no-cache make gcc g++ python linux-headers udev nodejs git && \
    npm install --unsafe-perm && \
    apk del make gcc g++ python linux-headers udev git

# Entrypoint
ENTRYPOINT ["./run.sh"]
