name: Update zigbee-herdsman-converters
on:
  repository_dispatch:
    types: update_zigbee-herdsman-converters

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Do Something Based On Triggered Event Data
        run: 'echo "Triggered event text: ${{ github.event.client_payload.version }}"'
